### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by saluton-mundo** [Vandborg/SWRevealViewController-XamarinBinding#8]
Hi there, 

I am having significant issues building this project. Each time it errors on generating `Messaging.g.cs`

```

        [DllImport (LIBOBJC_DYLIB, EntryPoint="objc_msgSendSuper")]
        public extern static bool bool_objc_msgSendSuper (IntPtr receiver, IntPtr selector);
        [DllImport (LIBOBJC_DYLIB, EntryPoint="objc_msgSend")]
        public extern static void void_objc_msgSend_bool (IntPtr receiver, IntPtr selector, bool arg1);
        [DllImport (LIBOBJC_DYLIB, EntryPoint="objc_msgSendSuper")]
        public extern static void void_objc_msgSendSuper_bool (IntPtr receiver, IntPtr selector, bool arg1);
        [DllImport (LIBOBJC_DYLIB, EntryPoint="objc_msgSend")]
        public extern static global::System.Double Double_objc_msgSend (IntPtr receiver, IntPtr selector);
        [DllImport (LIBOBJC_DYLIB, EntryPoint="objc_msgSendSuper")]
        public extern static global::System.Double Double_objc_msgSendSuper (IntPtr receiver, IntPtr selector);
        [DllImport (LIBOBJC_DYLIB, EntryPoint="objc_msgSend")]
        public extern static void vo
```

My environment is as follows:

Dev PC Environment 

---

Visual Studio Professional 2015 Version 14.0.25123.00 Update 2
Xamarin 4.0.3.214 (0dd817c)
Xamarin.iOS 9.6.1.8 (3a25bf1)

Macbook (Agent) Environment

---

OS X El Capitan Version 10.11.4
Simulator Version 9.3
Xcode Version 7.3 (7D175)

I have tried creating a new Project for the bindings project and followed the walkthrough provided by Xamarin [here](https://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/walkthrough/)

However, I successfully built the example project [here](https://www.dropbox.com/s/egwiav3wlwej1n0/SWRevealExample.zip), alas, it depends on monotouch and therefore is out of date as I am using Xamarin.iOS. 

Please could you let me know how to build and resolve the `Messaging.g.cs` issue so I am able reference it's dll in my own project.

Many thanks

John

**Comment by Vandborg** [comment]
Hi John
Unfortunately I cannot help since I haven't had a Xamarin license for years. I've tried to get somebody else to take over the project, but it has been unsuccessful.

I'll update the readme to say the project is discontinued

**Comment by saluton-mundo** [comment]
Hi Vandborg, 

Xamarin is now a completely free framework and part of Visual Studio 2015 Community. You can find it [here](https://store.xamarin.com/)

Perhaps if we can resolve the issue I can find a curator to take over the project?

**Comment by Vandborg** [comment]
Hi John

Hmm, I've not done Xamarin for 3 years, so I'm not sure if I'm the right guy for the job. But I looked at the "mother" project, and it had it's last commit 1 year ago, so I'm not sure if that is supported anymore?
